---
apiVersion: v1
kind: Namespace
metadata:
  name: unbound
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: unbound
  name: unbound
  namespace: unbound
spec:
  replicas: 2
  selector:
    matchLabels:
      app: unbound
  template:
    metadata:
      labels:
        app: unbound
    spec:
      containers:
      - image: kter/my-unbound:v0.0.3
        name: unbound
        ports:
          - name: udp
            containerPort: 53
---
apiVersion: v1
kind: Service
metadata:
  name: unbound
  namespace: unbound
  labels:
    app: unbound
spec:
  ports:
    - name: dns
      port: 53
      protocol: UDP
  selector:
    app: unbound
  type: LoadBalancer
