apiVersion: v1
kind: Namespace
metadata:
  name: logging

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsyslog-server
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rsyslog-server
  template:
    metadata:
      labels:
        app: rsyslog-server
    spec:
      containers:
      - name: rsyslog-server
        image: kter/my-rsyslog
        ports:
        - containerPort: 514

---

apiVersion: v1
kind: Service
metadata:
  name: rsyslog-service
  namespace: logging
spec:
  type: LoadBalancer
  ports:
  - name: udp
    port: 514
    targetPort: 514
    protocol: UDP
  selector:
    app: rsyslog-server

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output-cloudwatch.conf

  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10

  filter-kubernetes.conf: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Merge_Log           On
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off

  output-cloudwatch.conf: |
    [OUTPUT]
        Name                          cloudwatch
        Match                         *
        region                        ap-northeast-1
        log_group_name                /fluent-bit-cloudwatch/kubernetes
        log_stream_prefix             from-fluent-bit-
        auto_create_group             true

  parsers.conf: |
    [PARSER]
        Name                 json
        Format               json
        Time_Key             time
        Time_Format          %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name                 docker
        Format               json
        Time_Key             time
        Time_Format          %Y-%m-%dT%H:%M:%S.%L
        Time_Keep            On

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: logging
  labels:
    app.kubernetes.io/name: fluent-bit
spec:
  selector:
    matchLabels:
      name: fluent-bit
  template:
    metadata:
      labels:
        name: fluent-bit
    spec:
      containers:
      - name: fluent-bit
        image: public.ecr.aws/aws-observability/aws-for-fluent-bit:stable
        env:
          # kubectl create secret generic aws-creds -n logging --from-literal=aws_access_key_id=<your-aws-access-key-id> --from-literal=aws_secret_access_key=<your-aws-secret-access-key>
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-creds
                key: aws_access_key_id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-creds
                key: aws_secret_access_key
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc/
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluent-bit-config
        configMap:
          name: fluent-bit-config

